name: CI
on:
  push:
    branches:
      - "**"
      - "!main"
jobs:
  PYPI:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: python -m pip install -r requirements.txt
      - name: Setup Package Version
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import toml
            metadata_file_path = './pyproject.toml'
            pypi_meta = toml.load(metadata_file_path)
            pypi_meta['project']['version'] = "${{ github.run_number }}.${{ github.run_attempt }}.${{ github.run_id }}"
            with open(metadata_file_path,'w') as f:
              toml.dump(pypi_meta, f)
      - name: Build Package
        run: python -m build
      - name: Test Install
        run: python -m pip install .
      - name: Test | initialize profile
        run: dotctl init -e dev
      - name: Test | list profiles
        run: dotctl list
      - name: Test | wipe profile
        run: dotctl wipe --no-confirm
